openapi: 3.0.0
info:
  version: 1.0.0
  title: File Difference API
paths:
  /login:
    post:
      description: login as our application's system user (postgrescrutiniser)
      operationId: postLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccessResponse'
        '500':
          description: Server side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        name:
          type: string
        password:
          type: string
    LoginSuccessResponse:
      type: object
      properties:
        token:
          type: string
          description: JWT access token for authenticated user
    ErrorMessage:
      type: object
      required:
        - error_message
      properties:
        error_message:
          type: string