openapi: 3.0.0
info:
  version: 1.0.0
  title: File Difference API
paths:
  /backup:
    get:
      description: get all postgresql.auto.conf backup files
      tags:
        - backup
      operationId: getBackups
      responses:
        '202':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackupFile'
        '401':
          description: Token missing or malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Server side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      description: removes all postgresql.auto.conf backup files
      tags:
        - backup
      operationId: deleteBackups
      responses:
        '204':
          description: success response
        '401':
          description: Token missing or malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Server side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /backup/{backup_name}:
    put:
      description: restores backup file specified by parameter
      tags:
        - backup
      operationId: putBackup
      parameters:
        - name: backup_name
          in: path
          description: file name of the backup to be restored
          required: true
          example: "postgresql.auto.conf_1679567712"
          schema:
            type: string
            # does not work with current version of oapi-codegen for some reason:
            pattern: ^postgresql.auto.conf_[0-9]{10}$
      responses:
        '205':
          description: file was successfully restored
        '400':
          description: Invalid parameter format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '401':
          description: Token missing or malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Server side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      description: delete a specific postgresql.auto.conf backup file
      tags:
        - backup
      operationId: deleteBackup
      parameters:
        - name: backup_name
          in: path
          description: Name of the backup file to delete
          required: true
          example: "postgresql.auto.conf_1679567712"
          schema:
            type: string
            pattern: ^postgresql.auto.conf_[0-9]{10}$
      responses:
        '204':
          description: success response
        '401':
          description: Token missing or malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Server side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /file-diff/{backup_name}:
    get:
      description: get difference between current postgresql.auto.conf file and a backup file
      tags:
        - file-diff
      operationId: getFileDiff
      parameters:
        - name: backup_name
          in: path
          description: Name of the backup file to diff against
          required: true
          example: "postgresql.auto.conf_1679567712"
          schema:
            type: string
            pattern: '^postgresql.auto.conf_[0-9]{10}$'
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileDiffResponse'
        '400':
          description: Invalid parameter format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '401':
          description: Token missing or malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Server side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  # 1) Define the security scheme type (HTTP bearer)
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    FileDiffResponse:
      type: object
      properties:
        filename:
          type: string
          description: the name of the file being compared
          example: "/usr/local/postgrescrutiniser/backups/postgresql.auto.conf_1679567270"
          # x-oapi-codegen-extra-tags:
          #   validate: gte=0
        time:
          type: string
          format: date-time
          description: timestamp for when the backup file was created
          example: "2023-03-23T12:27:50+02:00"
        diff:
          type: array
          example:
            - line: "# Do not edit this file manually!\n# It will be overwritten by the ALTER SYSTEM command.\n"
              type: "Equal"
            - line: "max_connections = '100'\nautovacuum_work_mem = '262145'\nhuge_pages = 'off'\n"
              type: "Insert"
          items:
            $ref: '#/components/schemas/FileDiffLine'
    FileDiffLine:
      type: object
      properties:
        line:
          type: string
          description: line that is compared between two files
        type:
          type: string
          enum: [Equal, Insert, Delete]
          description: specifies whether line has been added, removed or unchanged
    BackupFile:
      type: object
      properties:
        name:
          type: string
          description: name of the backup file
        time:
          type: string
          format: date-time
          description: timestamp for when the backup file was created
      example:
        - name: "postgresql.auto.conf_1679567240"
          time: "2023-03-23T12:27:20+02:00"
    ErrorMessage:
      type: object
      required:
        - error_message
      properties:
        error_message:
          type: string
# 2) Apply the security globally to all operations
security:
  - bearerAuth: []         # use the same name as above