// Package auth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package auth

// ErrorMessage defines model for ErrorMessage.
type ErrorMessage struct {
	ErrorMessage string `json:"error_message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Name     *string `json:"name,omitempty"`
	Password *string `json:"password,omitempty"`
}

// LoginSuccessResponse defines model for LoginSuccessResponse.
type LoginSuccessResponse struct {
	// Token JWT access token for authenticated user
	Token *string `json:"token,omitempty"`
}

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequest
