// Package auth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package auth

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xTUWvVTBD9K8t8H6gQmqviS94UFSoKpRV8EJF1M7l3a7KznZmtXsr977KT6jU14Esx",
	"T5uZM5xzZs/eQKApU8KkAt0NSNjh5O34ipn4HYr4Ldb/zJSRNaJ1sXY/T8e27jNCB6Ic0xYOhwYYr0pk",
	"7KH7eAf+qfkJpy+XGBQODbylbUzneFVQ9E+65Kc1lgayF/lG3K9LWGe5KCGgyDlKpiQr5pS+YqqHHiVw",
	"zBopQQdvPrx33kadIdxA7HzRHSaNwSv2rggyNH9XUksxDWRsUcfaex1HdC/jMCBjCuien51CA9fIMtM/",
	"PtmcbKoJyph8jtDBUyvVLejOlLdjNWiOaN7j0oK1nRdHhZ3Peay6I6UH4mQvipM5cA/r9JbraNGYoiA/",
	"AiNmg5/20MEZido+Yb5rFH1B/b6SBkqKyfh/I2kvhdIxZfX0P+MAHfzXHmPY3mawXSTisEyUckErzFdo",
	"3p9sNvfLfTcnpmG5T5khjn9hGnh2jzoWj3CF/wL5GtlJ7NHZGwODDL6M+s9ElITfM4aa/1sN9v0IAAD/",
	"/2hGfP1cBAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
