// Package file provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package file

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for FileDiffLineType.
const (
	Delete FileDiffLineType = "Delete"
	Equal  FileDiffLineType = "Equal"
	Insert FileDiffLineType = "Insert"
)

// BackupFile defines model for BackupFile.
type BackupFile struct {
	// Name name of the backup file
	Name string `json:"name"`

	// Time timestamp for when the backup file was created
	Time time.Time `json:"time"`
}

// ErrorMessage defines model for ErrorMessage.
type ErrorMessage struct {
	ErrorMessage string `json:"error_message"`
}

// FileDiffLine defines model for FileDiffLine.
type FileDiffLine struct {
	// Line line that is compared between two files
	Line string `json:"line"`

	// Type specifies whether line has been added, removed or unchanged
	Type FileDiffLineType `json:"type"`
}

// FileDiffLineType specifies whether line has been added, removed or unchanged
type FileDiffLineType string

// FileDiffResponse defines model for FileDiffResponse.
type FileDiffResponse struct {
	Diff []FileDiffLine `json:"diff"`

	// Filename the name of the file being compared
	Filename string `json:"filename"`

	// Time timestamp for when the backup file was created
	Time time.Time `json:"time"`
}
